# Generated by Django 3.1.3 on 2021-05-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210528_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.IntegerField()),
                ('identidad', models.IntegerField()),
                ('idmunicipio', models.IntegerField()),
                ('codigoactividad', models.IntegerField()),
                ('nombreempresa', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('codigopostal', models.IntegerField()),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmunicipio', models.IntegerField()),
                ('identidad', models.IntegerField()),
                ('nombremunicipio', models.CharField(max_length=200)),
            ],
        ),
    ]
